settings:
  pull_request:
    force: true
    labels:
      - 'files-sync'
    title: 'pull request title'
    body: |
      This PR contains the following updates:

      | :chart_with_upwards_trend: Change | :hammer_and_wrench: Synchronizing Repository | :link: Workflow |
      | :-- | :-- | :-- |
      | <%- changes.length %> files | [<%- repository %>](<%- github %>/<%- repository %>) | [\`<%- workflow %>#<%- run.number %>\`](<%- run.url %>) |

      ---

      ### All PR Titles

      <%_ for (const prTitle of pull_request_titles) { -%>
      - <%- prTitle %>
      <%_ } -%>
      <% } -%>
          `.trim(),

      ---
patterns:
  - files:
      - from: .
        to: .
        exclude:
          - README1.md
          - README3.md
    repositories:
      - michaelshih-circle/test-sync-target@main