settings:
  commit:
      # defaults to "chore: sync files with `owner/repo`"
      format: '<%- prefix %>: <%- subject %>'
      prefix: 'commit profix'
      subject: 'commit subject'
  pull_request:
    force: true
    labels:
      - 'files-sync'
    title: 'pull request title'
    body: 'pull request body'

patterns:
  - files:
      - from: .
        to: .
        exclude:
          - README1.md
    delete_files:
      - README.md
    repositories:
      - michaelshih-circle/test-sync-target@main