settings:
  pull_request:
    force: true
    labels:
      - 'files-sync'
    title: 'pull request title'
    body: 'pull request body'

patterns:
  - files:
      - from: .
        to: .
        exclude:
          - README1.md
          - README3.md
          - README4.md
    repositories:
      - michaelshih-circle/test-sync-target@main