settings:
  pull_request:
    force: true
    labels:
      - 'files-sync'
    title: 'pull request title'
    body: |
      This PR contains the following updates:

      | :chart_with_upwards_trend: Change | :hammer_and_wrench: Synchronizing Repository | :link: Workflow |
      | :-- | :-- | :-- |
      | <%- changes.length %> files | [<%- repository %>](<%- github %>/<%- repository %>) | [\`<%- workflow %>#<%- run.number %>\`](<%- run.url %>) |

      ---

      ### All PR Titles

      <%_ for (const title of pull_request_titles) { -%>
      - <%- title %>
      <%_ } -%>

      ---

      ### Changed Files

      <%_ for (const file of changes) { -%>
      <% if (file.deleted) { -%>
      - :x: **Deleted**: \`<%- file.to %>\`<% if (file.pull_request_title) { %> (from PR: [#<%- file.pull_request_number %>] <%- file.pull_request_title %>)<% } %>
      <% } else if (file.from === file.to) { -%>
      - :file_folder: \`<%- file.to %>\`<% if (file.pull_request_title) { %> (from PR: [#<%- file.pull_request_number %>] <%- file.pull_request_title %>)<% } %>
      <% } else { -%>
      - :arrow_right: \`<%- file.from %>\` → \`<%- file.to %>\`<% if (file.pull_request_title) { %> (from PR: [#<%- file.pull_request_number %>] <%- file.pull_request_title %>)<% } %>
      <% } -%>
      <%_ } -%>
patterns:
  - files:
      - from: .
        to: .
        exclude:
          - README1.md
          - README3.md
    repositories:
      - michaelshih-circle/test-sync-target@main