name: 'Files Sync'
description: 'A customizable action that synchronizes files across multiple repositories.'
author: 'wadackel'
branding:
  color: white
  icon: git-pull-request

inputs:
  github_token:
    description: 'Personal Access Token to use to create file sync and PR. Required if `GITHUB_APP_*` is not specified.'
    required: true
  github_api_url:
    description: 'API URL of the GitHub server.'
    default: 'https://api.github.com'
  config_file:
    description: 'The path for the sync configuration file.'
    default: '.github/files-sync-config.yaml'

outputs:
  pull_request_urls:
    description: 'URL array of PRs created to synchronize files.'
  synced_files:
    description: 'An array of all synchronized file names.'

runs:
  using: 'node20'
  main: 'dist/index.js'
