name: pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    types: [ checks_requested ]

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v2
        with:
          repository: michaelshih-circle/test-sync-source
          token: "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"
          path: .

      - name: Checkout Repo B
        uses: actions/checkout@v2
        with:
          repository: michaelshih-circle/test-sync-target
          token: "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"
          path: .

      - name: Sync files from A to B
        run: |
          EXCLUDE_FILES=("README1.md")

          rsync -av --exclude=${EXCLUDE_FILES[@]} . .
          
          cd .
          git add .
          git commit -m "Sync files from Repo A" || echo "No changes to commit"
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Your Custom PR Title'  # 自定义 PR 标题
          body: 'This PR contains synced files from Repo A.'
          base: main  # 目标分支
          head: sync-branch-${{ github.sha }}  # 为 PR 创建的新分支