name: pipeline
on:
  push:
    branches: [main]
  merge_group:
    types: [ checks_requested ]

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./files-sync-action
        with:
          github_token: ${{ secrets.SECRET_TOKEN }}

