name: pipeline
on:
  push:
    branches: [main]
  merge_group:
    types: [ checks_requested ]

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  sync:
    - uses: ./.github/workflows/repo-file-sync.yml

